#pragma once

#include <Blitters/Blitter/BlitPlainXlat.h>
#include <Blitters/Blitter/BlitPlainXlatAlpha.h>
#include <Blitters/Blitter/BlitPlainXlatZRead.h>
#include <Blitters/Blitter/BlitPlainXlatZReadWrite.h>
#include <Blitters/Blitter/BlitTransDarken.h>
#include <Blitters/Blitter/BlitTransDarkenZRead.h>
#include <Blitters/Blitter/BlitTransDarkenZReadWrite.h>
#include <Blitters/Blitter/BlitTransLucent25.h>
#include <Blitters/Blitter/BlitTransLucent25Alpha.h>
#include <Blitters/Blitter/BlitTransLucent25AlphaZRead.h>
#include <Blitters/Blitter/BlitTransLucent25AlphaZReadWarp.h>
#include <Blitters/Blitter/BlitTransLucent25AlphaZReadWrite.h>
#include <Blitters/Blitter/BlitTransLucent25ZRead.h>
#include <Blitters/Blitter/BlitTransLucent25ZReadWarp.h>
#include <Blitters/Blitter/BlitTransLucent25ZReadWrite.h>
#include <Blitters/Blitter/BlitTransLucent50.h>
#include <Blitters/Blitter/BlitTransLucent50Alpha.h>
#include <Blitters/Blitter/BlitTransLucent50AlphaZRead.h>
#include <Blitters/Blitter/BlitTransLucent50AlphaZReadWarp.h>
#include <Blitters/Blitter/BlitTransLucent50AlphaZReadWrite.h>
#include <Blitters/Blitter/BlitTranslucent50NonzeroAlpha.h>
#include <Blitters/Blitter/BlitTranslucent50ZeroAlpha.h>
#include <Blitters/Blitter/BlitTransLucent50ZRead.h>
#include <Blitters/Blitter/BlitTransLucent50ZReadWarp.h>
#include <Blitters/Blitter/BlitTransLucent50ZReadWrite.h>
#include <Blitters/Blitter/BlitTransLucent75.h>
#include <Blitters/Blitter/BlitTransLucent75Alpha.h>
#include <Blitters/Blitter/BlitTransLucent75AlphaZRead.h>
#include <Blitters/Blitter/BlitTransLucent75AlphaZReadWarp.h>
#include <Blitters/Blitter/BlitTransLucent75AlphaZReadWrite.h>
#include <Blitters/Blitter/BlitTransLucent75ZRead.h>
#include <Blitters/Blitter/BlitTransLucent75ZReadWarp.h>
#include <Blitters/Blitter/BlitTransLucent75ZReadWrite.h>
#include <Blitters/Blitter/BlitTranslucentWriteAlpha.h>
#include <Blitters/Blitter/BlitTransRemapDest.h>
#include <Blitters/Blitter/BlitTransRemapXlat.h>
#include <Blitters/Blitter/BlitTransXlat.h>
#include <Blitters/Blitter/BlitTransXlatAlpha.h>
#include <Blitters/Blitter/BlitTransXlatAlphaZRead.h>
#include <Blitters/Blitter/BlitTransXlatAlphaZReadWrite.h>
#include <Blitters/Blitter/BlitTransXlatMultWriteAlpha.h>
#include <Blitters/Blitter/BlitTransXlatWriteAlpha.h>
#include <Blitters/Blitter/BlitTransXlatZRead.h>
#include <Blitters/Blitter/BlitTransXlatZReadWrite.h>
#include <Blitters/Blitter/BlitTransZRemapXlat.h>
#include <Blitters/Blitter/BlitTransZRemapXlatAlpha.h>
#include <Blitters/Blitter/BlitTransZRemapXlatAlphaZRead.h>
#include <Blitters/Blitter/BlitTransZRemapXlatAlphaZReadWrite.h>
#include <Blitters/Blitter/BlitTransZRemapXlatZRead.h>
#include <Blitters/Blitter/BlitTransZremapXlatZReadWrite.h>
